# Generated by Django 5.1.4 on 2025-12-16 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Component Categories',
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'E1 - Office', 'E2 - Industrial'", max_length=50)),
                ('pi_e_factor', models.FloatField(help_text='Environmental Factor value (e.g., 1.0, 2.0, 4.0)')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lambda_ref', models.FloatField(help_text='Base Failure Rate in FIT (Failures in 10^9 hours)')),
                ('ref_temp', models.FloatField(default=40.0, help_text='Reference Ambient Temperature in °C (usually 40)')),
                ('ref_voltage_ratio', models.FloatField(default=1.0, help_text='Reference Voltage stress ratio (e.g. 0.5 or 1.0)')),
                ('activation_energy', models.FloatField(default=0.0, help_text='Activation Energy (Ea) in eV. E.g., 0.35 for Ceramic Caps.')),
                ('c1_factor', models.FloatField(default=0.0, help_text='Voltage Constant C1 (or C3 in some tables)')),
                ('c2_factor', models.FloatField(default=0.0, help_text='Voltage Constant C2')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='api.componentcategory')),
            ],
        ),
    ]
