# Generated by Django 5.1.4 on 2025-12-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='componenttype',
            name='rated_power',
            field=models.FloatField(default=0.0, help_text='Rated Power in Watts (P_rat)'),
        ),
        migrations.AddField(
            model_name='componenttype',
            name='thermal_resistance',
            field=models.FloatField(default=0.0, help_text='R_th in K/W (Degrees rise per Watt)'),
        ),
        migrations.AlterField(
            model_name='componenttype',
            name='activation_energy',
            field=models.FloatField(default=0.0, help_text='Activation Energy (Ea) in eV'),
        ),
        migrations.AlterField(
            model_name='componenttype',
            name='c1_factor',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='componenttype',
            name='c2_factor',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='componenttype',
            name='lambda_ref',
            field=models.FloatField(help_text='Base Failure Rate in FIT'),
        ),
        migrations.AlterField(
            model_name='componenttype',
            name='ref_temp',
            field=models.FloatField(default=40.0),
        ),
        migrations.AlterField(
            model_name='componenttype',
            name='ref_voltage_ratio',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='environment',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='environment',
            name='pi_e_factor',
            field=models.FloatField(),
        ),
    ]
