# Generated by Django 5.1.4 on 2025-12-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_componenttype_rated_power_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componenttype',
            name='c3_factor',
            field=models.FloatField(default=0.0, help_text='Current Constant C3 (for Pi_I)'),
        ),
        migrations.AddField(
            model_name='componenttype',
            name='c4_factor',
            field=models.FloatField(default=0.0, help_text='Current Constant C4 (for Pi_I)'),
        ),
    ]
